---
title: "Contract"
author: "marcsole96"
date: "2021-11-02"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Setup
```{r echo=TRUE}
#setwd("../PIB_workflowr/data")
getwd()
```

```{r include=FALSE}
library(tidyverse)
library(ggplot2)
library(ggfortify)
library(Rtsne)
library(reshape2)
library(ggpubr)
library(plotly)
library(caret)
theme_set(theme_minimal(base_size=14,base_family = "serif"))
```

# Opening the data workspace
```{r echo=TRUE}
load("wrangling.RData")
```

# Data analysis
## Visualizations
### PCA
```{r}
labels<-contract$labels

data <- contract %>%
  select(-labels)

data<-as.matrix(data)
rownames(data) <- NULL

pr.out <- prcomp(data,scale=FALSE)

dat_3d <- pr.out$x[,1:3] %>% as_tibble() %>% mutate(square = contract$labels)

fig <- plot_ly(dat_3d, x = ~PC1, y = ~PC2, z = ~PC3, 
               color = ~square,colors=c('#8dc5f0','#43abf9','#0092ff','#cef37b','#a6d045','#7caa16','#f8bc7d','#e0892e','#ff8200'), size = I(100))
fig <- fig %>% add_markers()
fig <- fig %>% layout(scene = list(xaxis = list(title = 'PC1'),
                                   yaxis = list(title = 'PC2'),
                                   zaxis = list(title = 'PC3')))

fig
```





## Models
### GLMNET With Caret
```{r warning=FALSE}
training_x <- training_DF %>% select(-labels) %>% as.data.frame()
training_y <- training_DF$labels

trControl <- trainControl(method = "loocv", number = 5, verboseIter = F)

fit <- train(x = training_x, 
             y = training_y, 
        method = "glmnet",
        tuneLength = 5,
     trControl = trControl
    )

newdata = contract[,-1]
(predicted<- predict(fit, newdata = contract[,-1]))
(predicted<- predict(fit, newdata = contract[,-1],type = "prob"))
```

#### Plots

##### Page 1
```{r fig.height=4, fig.width=10, message=FALSE, warning=FALSE}
toplot<-as.data.frame(t(predicted))
names(toplot)<-c(contract$labels)
toplot<-toplot %>% mutate(Pens=c("Pen 1", "Pen 2", "Pen 3", "Pen 4", "Pen 5", "Pen 6"))

X_Labels <- c("1","2","3","4","5","6")

PG1_II<-toplot %>% select(II_initials_page_1,Pens) %>% ggplot(aes(x=Pens, y=II_initials_page_1, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,II_initials_page_1, label=round(II_initials_page_1,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG1_III<-toplot %>% select(III_initials_page_1,Pens) %>% ggplot(aes(x=Pens, y=III_initials_page_1, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,III_initials_page_1, label=round(III_initials_page_1,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG1_SF<-toplot %>% select(SF_initials_page_1,Pens) %>% ggplot(aes(x=Pens, y=SF_initials_page_1, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,SF_initials_page_1, label=round(SF_initials_page_1,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

figure<-ggarrange(PG1_II, PG1_III, PG1_SF,
                    labels = c("II", "III", "SF"),font.label=list(color="black",size=9),
                    ncol = 3, nrow = 1,common.legend=T,legend="none")

annotate_figure(figure,top = text_grob("Contract Pg.1 GLMNET", color = "Black", face = "bold", size = 14,family = "serif"))
```

##### Page 2
```{r fig.height=4, fig.width=10}
PG2_II<-toplot %>% select(II_initials_page_2,Pens) %>% ggplot(aes(x=Pens, y=II_initials_page_2, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,II_initials_page_2, label=round(II_initials_page_2,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG2_III<-toplot %>% select(III_initials_page_2,Pens) %>% ggplot(aes(x=Pens, y=III_initials_page_2, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,III_initials_page_2, label=round(III_initials_page_2,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG2_SF<-toplot %>% select(SF_initials_page_2,Pens) %>% ggplot(aes(x=Pens, y=SF_initials_page_2, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,SF_initials_page_2, label=round(SF_initials_page_2,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

figure<-ggarrange(PG2_II, PG2_III, PG2_SF,
                    labels = c("II", "III", "SF"),font.label=list(color="black",size=9),
                    ncol = 3, nrow = 1,common.legend=T,legend="none")

annotate_figure(figure,top = text_grob("Contract Pg.2 GLMNET", color = "Black", face = "bold", size = 14,family = "serif"))
```

##### Page 3
```{r fig.height=4, fig.width=10}
PG3_II<-toplot %>% select(II_initials_signature_page_3,Pens) %>% ggplot(aes(x=Pens, y=II_initials_signature_page_3, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,II_initials_signature_page_3, label=round(II_initials_signature_page_3,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG3_III<-toplot %>% select(III_initials_signature_page_3,Pens) %>% ggplot(aes(x=Pens, y=III_initials_signature_page_3, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,III_initials_signature_page_3, label=round(III_initials_signature_page_3,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG3_SF<-toplot %>% select(SFsignature_page_3,Pens) %>% ggplot(aes(x=Pens, y=SFsignature_page_3, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,SFsignature_page_3, label=round(SFsignature_page_3,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

figure<-ggarrange(PG3_II, PG3_III, PG3_SF,
                    labels = c("II", "III", "SF"),font.label=list(color="black",size=9),
                    ncol = 3, nrow = 1,common.legend=T,legend="none")

annotate_figure(figure,top = text_grob("Contract Pg.3 GLMNET", color = "Black", face = "bold", size = 14,family = "serif"))
```

```{r}
figure<-ggarrange(PG1_II, PG1_III, PG1_SF,PG2_II, PG2_III, PG2_SF,PG3_II, PG3_III, PG3_SF,
                    labels = c("PG1_II", "PG1_III", "PG1_SF","PG2_II", "PG2_III", "PG2_SFq","PG3_II", "PG3_III", "PG3_SF"),font.label=list(color="black",size=9),
                    ncol = 3, nrow = 3,common.legend=T,legend="none")

annotate_figure(figure,top = text_grob("GLMNET default parameters", color = "Black", face = "bold", size = 14,family = "serif"))
```


### Caret model GLMNET Lasso (Alpha = 1) Lambda ranging from 0 to 1
```{r warning=FALSE}
training_x <- training_DF %>% select(-labels) %>% as.data.frame()
training_y <- training_DF$labels

trControl <- trainControl(method = "loocv", number = 5, verboseIter = F)
tuneGrid <- expand.grid(alpha = 1, lambda = seq(0.001, 1, length = 1000))

fit <- train(x = training_x, 
             y = training_y, 
        method = "glmnet",
        tuneLength = 5,
     trControl = trControl,
     tuneGrid = tuneGrid
    )

newdata = contract[,-1]
(predicted<- predict(fit, newdata = contract[,-1]))
(predicted<- predict(fit, newdata = contract[,-1],type = "prob"))
```

#### Plots

##### Page 1
```{r fig.height=4, fig.width=10, message=FALSE, warning=FALSE}
toplot<-as.data.frame(t(predicted))
names(toplot)<-c(contract$labels)
toplot<-toplot %>% mutate(Pens=c("Pen 1", "Pen 2", "Pen 3", "Pen 4", "Pen 5", "Pen 6"))

X_Labels <- c("1","2","3","4","5","6")

PG1_II<-toplot %>% select(II_initials_page_1,Pens) %>% ggplot(aes(x=Pens, y=II_initials_page_1, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,II_initials_page_1, label=round(II_initials_page_1,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG1_III<-toplot %>% select(III_initials_page_1,Pens) %>% ggplot(aes(x=Pens, y=III_initials_page_1, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,III_initials_page_1, label=round(III_initials_page_1,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG1_SF<-toplot %>% select(SF_initials_page_1,Pens) %>% ggplot(aes(x=Pens, y=SF_initials_page_1, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,SF_initials_page_1, label=round(SF_initials_page_1,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

figure<-ggarrange(PG1_II, PG1_III, PG1_SF,
                    labels = c("II", "III", "SF"),font.label=list(color="black",size=9),
                    ncol = 3, nrow = 1,common.legend=T,legend="none")

annotate_figure(figure,top = text_grob("Contract Pg.1 GLMNET", color = "Black", face = "bold", size = 14,family = "serif"))
```

##### Page 2
```{r fig.height=4, fig.width=10}
PG2_II<-toplot %>% select(II_initials_page_2,Pens) %>% ggplot(aes(x=Pens, y=II_initials_page_2, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,II_initials_page_2, label=round(II_initials_page_2,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG2_III<-toplot %>% select(III_initials_page_2,Pens) %>% ggplot(aes(x=Pens, y=III_initials_page_2, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,III_initials_page_2, label=round(III_initials_page_2,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG2_SF<-toplot %>% select(SF_initials_page_2,Pens) %>% ggplot(aes(x=Pens, y=SF_initials_page_2, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,SF_initials_page_2, label=round(SF_initials_page_2,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

figure<-ggarrange(PG2_II, PG2_III, PG2_SF,
                    labels = c("II", "III", "SF"),font.label=list(color="black",size=9),
                    ncol = 3, nrow = 1,common.legend=T,legend="none")

annotate_figure(figure,top = text_grob("Contract Pg.2 GLMNET", color = "Black", face = "bold", size = 14,family = "serif"))
```

##### Page 3
```{r fig.height=4, fig.width=10}
PG3_II<-toplot %>% select(II_initials_signature_page_3,Pens) %>% ggplot(aes(x=Pens, y=II_initials_signature_page_3, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,II_initials_signature_page_3, label=round(II_initials_signature_page_3,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG3_III<-toplot %>% select(III_initials_signature_page_3,Pens) %>% ggplot(aes(x=Pens, y=III_initials_signature_page_3, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,III_initials_signature_page_3, label=round(III_initials_signature_page_3,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG3_SF<-toplot %>% select(SFsignature_page_3,Pens) %>% ggplot(aes(x=Pens, y=SFsignature_page_3, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,SFsignature_page_3, label=round(SFsignature_page_3,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

figure<-ggarrange(PG3_II, PG3_III, PG3_SF,
                    labels = c("II", "III", "SF"),font.label=list(color="black",size=9),
                    ncol = 3, nrow = 1,common.legend=T,legend="none")

annotate_figure(figure,top = text_grob("Contract Pg.3 GLMNET", color = "Black", face = "bold", size = 14,family = "serif"))
```

```{r}
figure<-ggarrange(PG1_II, PG1_III, PG1_SF,PG2_II, PG2_III, PG2_SF,PG3_II, PG3_III, PG3_SF,
                    labels = c("PG1_II", "PG1_III", "PG1_SF","PG2_II", "PG2_III", "PG2_SFq","PG3_II", "PG3_III", "PG3_SF"),font.label=list(color="black",size=9),
                    ncol = 3, nrow = 3,common.legend=T,legend="none")

annotate_figure(figure,top = text_grob("GLMNET Lasso", color = "Black", face = "bold", size = 14,family = "serif"))
```

### RF with Caret
```{r warning=FALSE}
training_x <- training_DF %>% select(-labels) %>% as.data.frame()
training_y <- training_DF$labels

trControl <- trainControl(method = "loocv", number = 5, verboseIter = F)

fit <- train(x = training_x, 
             y = training_y, 
        method = "rf",
        tuneLength = 5,
     trControl = trControl
    )

newdata = contract[,-1]
(predicted<- predict(fit, newdata = contract[,-1]))
(predicted<- predict(fit, newdata = contract[,-1],type = "prob"))
```

#### Plots

##### Page 1
```{r fig.height=4, fig.width=10, message=FALSE, warning=FALSE}
toplot<-as.data.frame(t(predicted))
names(toplot)<-c(contract$labels)
toplot<-toplot %>% mutate(Pens=c("Pen 1", "Pen 2", "Pen 3", "Pen 4", "Pen 5", "Pen 6"))

X_Labels <- c("1","2","3","4","5","6")

PG1_II<-toplot %>% select(II_initials_page_1,Pens) %>% ggplot(aes(x=Pens, y=II_initials_page_1, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,II_initials_page_1, label=round(II_initials_page_1,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG1_III<-toplot %>% select(III_initials_page_1,Pens) %>% ggplot(aes(x=Pens, y=III_initials_page_1, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,III_initials_page_1, label=round(III_initials_page_1,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG1_SF<-toplot %>% select(SF_initials_page_1,Pens) %>% ggplot(aes(x=Pens, y=SF_initials_page_1, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,SF_initials_page_1, label=round(SF_initials_page_1,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

figure<-ggarrange(PG1_II, PG1_III, PG1_SF,
                    labels = c("II", "III", "SF"),font.label=list(color="black",size=9),
                    ncol = 3, nrow = 1,common.legend=T,legend="none")

annotate_figure(figure,top = text_grob("Contract Pg.1 GLMNET", color = "Black", face = "bold", size = 14,family = "serif"))
```

##### Page 2
```{r fig.height=4, fig.width=10}
PG2_II<-toplot %>% select(II_initials_page_2,Pens) %>% ggplot(aes(x=Pens, y=II_initials_page_2, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,II_initials_page_2, label=round(II_initials_page_2,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG2_III<-toplot %>% select(III_initials_page_2,Pens) %>% ggplot(aes(x=Pens, y=III_initials_page_2, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,III_initials_page_2, label=round(III_initials_page_2,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG2_SF<-toplot %>% select(SF_initials_page_2,Pens) %>% ggplot(aes(x=Pens, y=SF_initials_page_2, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,SF_initials_page_2, label=round(SF_initials_page_2,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

figure<-ggarrange(PG2_II, PG2_III, PG2_SF,
                    labels = c("II", "III", "SF"),font.label=list(color="black",size=9),
                    ncol = 3, nrow = 1,common.legend=T,legend="none")

annotate_figure(figure,top = text_grob("Contract Pg.2 GLMNET", color = "Black", face = "bold", size = 14,family = "serif"))
```

##### Page 3
```{r fig.height=4, fig.width=10}
PG3_II<-toplot %>% select(II_initials_signature_page_3,Pens) %>% ggplot(aes(x=Pens, y=II_initials_signature_page_3, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,II_initials_signature_page_3, label=round(II_initials_signature_page_3,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG3_III<-toplot %>% select(III_initials_signature_page_3,Pens) %>% ggplot(aes(x=Pens, y=III_initials_signature_page_3, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,III_initials_signature_page_3, label=round(III_initials_signature_page_3,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

PG3_SF<-toplot %>% select(SFsignature_page_3,Pens) %>% ggplot(aes(x=Pens, y=SFsignature_page_3, fill=Pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(Pens,SFsignature_page_3, label=round(SFsignature_page_3,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "") + scale_color_discrete(name = "Pens")

figure<-ggarrange(PG3_II, PG3_III, PG3_SF,
                    labels = c("II", "III", "SF"),font.label=list(color="black",size=9),
                    ncol = 3, nrow = 1,common.legend=T,legend="none")

annotate_figure(figure,top = text_grob("Contract Pg.3 GLMNET", color = "Black", face = "bold", size = 14,family = "serif"))
```

```{r}
figure<-ggarrange(PG1_II, PG1_III, PG1_SF,PG2_II, PG2_III, PG2_SF,PG3_II, PG3_III, PG3_SF,
                    labels = c("PG1_II", "PG1_III", "PG1_SF","PG2_II", "PG2_III", "PG2_SFq","PG3_II", "PG3_III", "PG3_SF"),font.label=list(color="black",size=9),
                    ncol = 3, nrow = 3,common.legend=T,legend="none")
annotate_figure(figure,top = text_grob("Random Forests", color = "Black", face = "bold", size = 14,family = "serif"))
```
