---
title: "Models"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Setup
```{r include=FALSE}
#setwd("../PIB_workflowr/data")
getwd()
```

```{r include=FALSE}
library(tidyverse)
library(ggplot2)
library(ggfortify)
library(Rtsne)
library(reshape2)
library(ggpubr)
library(caret)
theme_set(theme_minimal(base_family = "Calibri"))
```

# Opening the data workspace
```{r echo=TRUE}
load("wrangling.RData")
```

# CARET models
## Caret model GLMNET
```{r message=FALSE, warning=FALSE}
training_x <- training_DF %>% select(-labels) %>% as.data.frame()
training_y <- training_DF$labels

trControl <- trainControl(method = "LOOCV", number = 5, verboseIter = F)

fit <- train(x = training_x, 
             y = training_y, 
        method = "glmnet",
        tuneLength = 5,
     trControl = trControl
    )

#print(fit)

# importance <- varImp(fit,scale=FALSE)
# 
# importance_DF<-importance$importance
# plot(importance,top=10)
# 
# importance_DF<-melt(importance_DF)
# 
# 
# ggplot(importance_DF)+geom_point(aes(x=value,y=variable, color=variable))

(predicted<- predict(fit, newdata = test_data[,-1],type = "prob"))
(predict(fit, newdata = test_data[,-1]))
```

### Plots
```{r fig.height=5, fig.width=10, message=FALSE, warning=FALSE}

toplot<-as.data.frame(t(predicted))
names(toplot)<-c("strike1","strike2","strike3","strike4","strike5","strike6")
toplot<-toplot %>% mutate(pens=row.names(toplot))

strike1<-toplot %>% select(strike1,pens) %>% ggplot(aes(x=pens, y=strike1, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike1, label=round(strike1,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+
  ggtitle("Strike 1 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike2<-toplot %>% select(strike2,pens) %>% ggplot(aes(x=pens, y=strike2, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike2, label=round(strike2,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 2 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike3<-toplot %>% select(strike3,pens) %>% ggplot(aes(x=pens, y=strike3, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike3, label=round(strike3,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 3 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike4<-toplot %>% select(strike4,pens) %>% ggplot(aes(x=pens, y=strike4, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike4, label=round(strike4,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 4 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike5<-toplot %>% select(strike5,pens) %>% ggplot(aes(x=pens, y=strike5, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike5, label=round(strike5,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 5 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike6<-toplot %>% select(strike6,pens) %>% ggplot(aes(x=pens, y=strike6, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike6, label=round(strike6,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 6 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")


plot<-ggarrange(strike1, strike2, strike3, strike4, strike5, strike6,
                    ncol = 3, nrow = 3,common.legend = TRUE,legend="none")


annotate_figure(plot, top = text_grob("GLMNET default parameters", 
               color = "black", face = "bold", size = 14))
```



## Caret model GLMNET Lasso (Alpha = 1) Lambda ranging from 0 to 1
```{r message=FALSE, warning=FALSE}
training_x <- training_DF %>% select(-labels) %>% as.data.frame()
training_y <- training_DF$labels

trControl <- trainControl(method = "LOOCV", number = 5, verboseIter = F)


tuneGrid <- expand.grid(alpha = 1, lambda = seq(0.001, 1, length = 1000))

fit <- train(x = training_x, 
             y = training_y, 
        method = "glmnet",
        tuneGrid = tuneGrid,
     trControl = trControl,
    )

#print(fit)

ggplot(fit)

(predicted<- predict(fit, newdata = test_data[,-1],type = "prob"))
(predict(fit, newdata = test_data[,-1]))
```

### Plots
```{r fig.height=5, fig.width=10, message=FALSE, warning=FALSE}

toplot<-as.data.frame(t(predicted))
names(toplot)<-c("strike1","strike2","strike3","strike4","strike5","strike6")
toplot<-toplot %>% mutate(pens=row.names(toplot))

strike1<-toplot %>% select(strike1,pens) %>% ggplot(aes(x=pens, y=strike1, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike1, label=round(strike1,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+
  ggtitle("Strike 1 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike2<-toplot %>% select(strike2,pens) %>% ggplot(aes(x=pens, y=strike2, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike2, label=round(strike2,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 2 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike3<-toplot %>% select(strike3,pens) %>% ggplot(aes(x=pens, y=strike3, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike3, label=round(strike3,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 3 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike4<-toplot %>% select(strike4,pens) %>% ggplot(aes(x=pens, y=strike4, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike4, label=round(strike4,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 4 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike5<-toplot %>% select(strike5,pens) %>% ggplot(aes(x=pens, y=strike5, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike5, label=round(strike5,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 5 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike6<-toplot %>% select(strike6,pens) %>% ggplot(aes(x=pens, y=strike6, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike6, label=round(strike6,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 6 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")


plot<-ggarrange(strike1, strike2, strike3, strike4, strike5, strike6,
                    ncol = 3, nrow = 3,common.legend = TRUE,legend="none")


annotate_figure(plot, top = text_grob("GLMNET Lasso", 
               color = "black", face = "bold", size = 14))
```


## Let's try RFs again...
```{r}
training_x <- training_DF %>% select(-labels) %>% as.data.frame()
training_y <- training_DF$labels

trControl <- trainControl(method = "LOOCV", number = 5, verboseIter = F)


fit <- train(x = training_x, 
             y = training_y, 
        method = "rf",
        tuneLength = 10,
     trControl = trControl,
    )

(predicted<- predict(fit, newdata = test_data[,-1],type = "prob"))
(predict(fit, newdata = test_data[,-1]))
```

### Plots
```{r fig.height=5, fig.width=10, message=FALSE, warning=FALSE}

toplot<-as.data.frame(t(predicted))
names(toplot)<-c("strike1","strike2","strike3","strike4","strike5","strike6")
toplot<-toplot %>% mutate(pens=row.names(toplot))

strike1<-toplot %>% select(strike1,pens) %>% ggplot(aes(x=pens, y=strike1, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike1, label=round(strike1,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+
  ggtitle("Strike 1 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike2<-toplot %>% select(strike2,pens) %>% ggplot(aes(x=pens, y=strike2, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike2, label=round(strike2,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 2 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike3<-toplot %>% select(strike3,pens) %>% ggplot(aes(x=pens, y=strike3, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike3, label=round(strike3,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 3 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike4<-toplot %>% select(strike4,pens) %>% ggplot(aes(x=pens, y=strike4, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike4, label=round(strike4,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 4 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike5<-toplot %>% select(strike5,pens) %>% ggplot(aes(x=pens, y=strike5, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike5, label=round(strike5,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 5 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")

strike6<-toplot %>% select(strike6,pens) %>% ggplot(aes(x=pens, y=strike6, fill=pens)) +
  geom_bar(stat="identity",position=position_stack())+
  geom_text(aes(pens,strike6, label=round(strike6,3)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette="Accent")+ ggtitle("Strike 6 GLMNET predictions")+
  theme(axis.title=element_text(size=12),axis.text=element_text(size=10),plot.title = element_text(hjust = 0.5, size=10, face = "bold"), strip.text.x = element_text(size = 10))+ 
  labs(y="Probability", x = "Pens") + scale_color_discrete(name = "Pens")


plot<-ggarrange(strike1, strike2, strike3, strike4, strike5, strike6,
                    ncol = 3, nrow = 3,common.legend = TRUE,legend="none")


annotate_figure(plot, top = text_grob("Random Forests", 
               color = "black", face = "bold", size = 14))
```
