---
title: "Data Wrangling"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Setup

```{r Working directory, echo=TRUE}
#setwd("../PIB_workflowr/data")
getwd()
```

```{r Library load, echo=TRUE}
library(tidyverse)
library(ggplot2)
library(ggfortify)
library(Rtsne)
library(reshape2)
library(ggpubr)
theme_set(theme_minimal())
```

# Data Loading

## CONTRACT REGION OF INTERESTED EXPORTS

### Page 1 contract exports

```{r}
x <- read_tsv("filenames.tsv")

x$fullpath <- paste("", x$filename, sep="")
r <- list()

for (i in 1:nrow(x)) {

  tmp <- read_tsv(x$fullpath[i], col_names = F, col_types = "dd")

  names(tmp) <- c("mz", "intensity")

  tmp <- tmp %>% bind_cols(x[i,])

  r[[length(r)+1]] <- tmp

}

df <- bind_rows(r)
df$pen<-as.character(df$pen)
str(df)

write_rds(df, file = "full_data.rds")

rm(r,tmp,x)
```


```{r}
training_DF<-df%>%filter(group=="training") %>% select(mz,intensity,pen,filename) 
training_DF<-spread(training_DF,key=mz,value=intensity)
training_DF<-rename(training_DF,labels=pen)
training_DF<-training_DF[-2]
```

```{r}
test_data<-df%>%filter(group=="test") %>% select(mz,intensity,pen,filename) 
test_data<-spread(test_data,key=mz,value=intensity)
test_data<-rename(test_data,labels=pen)
test_data<-test_data[-2]
```

```{r}
contract<-df%>%filter(group=="contract") %>% select(mz,intensity,filename) 
contract<-spread(contract,key=mz,value=intensity)
contract<-rename(contract,labels=filename)
contract<-contract[-2]
```

```{r}
rm(df)
```

## Contract
### Page 1 contract exports

```{r Page 1 contract exports, echo=TRUE}

p1_initials_II <- read.table(file = "CONTRACT REGION OF INTERESTED EXPORTS/Page 1 contract exports/190910,21h19_II initials page 1.txt", sep = "")

p1_initials_III <- read.table(file = "CONTRACT REGION OF INTERESTED EXPORTS/Page 1 contract exports/190910,21h19_III initials page 1.txt", sep = "")

p1_initials_SF <- read.table(file = "CONTRACT REGION OF INTERESTED EXPORTS/Page 1 contract exports/190910,21h19_SF initials page 1.txt", sep = "")


colnames(p1_initials_SF) <- c("spectrum", "Page1_initials_SF")
colnames(p1_initials_II) <- c("spectrum", "Page1_initials_II")
colnames(p1_initials_III) <- c("spectrum", "Page1_initials_III")
```

### Page 2 contract exports

```{r Page 2 contract exports, echo=TRUE}

p2_initials_II <- read.table(file = "CONTRACT REGION OF INTERESTED EXPORTS/Page 2 contract exports/190910,23h44_II initials page 2.txt", sep = "")

p2_initials_III <- read.table(file = "CONTRACT REGION OF INTERESTED EXPORTS/Page 2 contract exports/190910,23h44_III initials page 2.txt", sep = "")

p2_initials_SF <- read.table(file = "CONTRACT REGION OF INTERESTED EXPORTS/Page 2 contract exports/190910,23h44_SF initials page 2.txt", sep = "")

colnames(p2_initials_SF) <- c("spectrum", "Page2_initials_SF")
colnames(p2_initials_II) <- c("spectrum", "Page2_initials_II")
colnames(p2_initials_III) <- c("spectrum", "Page2_initials_III")

```

### Page 3 contract export

```{r Page 3 contract export, echo=TRUE}

p3_initials_II <- read.table(file = "CONTRACT REGION OF INTERESTED EXPORTS/Page 3 contract export/190910,01h50_II initials signature page 3.txt", sep = "")

p3_initials_III <- read.table(file = "CONTRACT REGION OF INTERESTED EXPORTS/Page 3 contract export/190910,01h50_III initials signature page 3.txt", sep = "")

p3_initials_SF <- read.table(file = "CONTRACT REGION OF INTERESTED EXPORTS/Page 3 contract export/190910,01h50_SFsignature page 3.txt", sep = "")

colnames(p3_initials_SF) <- c("spectrum", "Page3_signatures_SF")
colnames(p3_initials_II) <- c("spectrum", "Page3_signatures_II")
colnames(p3_initials_III) <- c("spectrum", "Page3_signatures_III")

```

### DF contract
```{r}
contract <-cbind(p1_initials_II,p1_initials_III[2],p1_initials_SF[2],p2_initials_II[2],p2_initials_III[2],p2_initials_SF[2],p3_initials_II[2],p3_initials_III[2],p3_initials_SF[2])

rm(p1_initials_II,p1_initials_III,p1_initials_SF,p2_initials_II,p2_initials_III,p2_initials_SF,p3_initials_II,p3_initials_III,p3_initials_SF,sq_beside_no4)

tcontract<-as.data.frame(t(contract[-1]))
names(tcontract)<-contract$spectrum
tcontract$labels=row.names(tcontract)
rownames(tcontract)<-c()
tcontract<-tcontract %>% 
  select(labels, everything())
contract<-tcontract
rm(tcontract)
```


# Resulting dataframes

I end up with two DFs, a training and a test DF

```{r}
(select(training_DF,1:5))
(select(test_data,1:5))
(select(contract,1:5))
```

## Saving the workspace to be used later

```{r}
save.image(file = "wrangling.RData")
```

